### PR TITLE
Follow enhance

### PR DESCRIPTION
**Pull request by patkamon**
Now follow status is handle for multiple calendar in one user.

changing:
1. ```is_valid``` now checking ```calendar_id``` too not only user as before.
2. ```calendar``` is new foreign key in fs model.
3. fs API now provide ```followed_calendar``` and ```followed_calendar_slug```

problems:
there are one problems in test_me I could not find ```calendar_id``` and ```calendar.id``` can't seem to work so I just randomly put ```1``` integer for those follow_post test that require ```follow_calendar```.

### CODE REVIEW

**Comment by natchanon-space** [comment]
@patkamon Since you add new field to the model, then where is the new fixture file for this?

**Review by HuskyIsHere — APPROVED** [review]

**Comment by patkamon** [comment]
> @patkamon Since you add new field to the model, then where is the new fixture file for this?
> 
> For your problem, In `test_me_post_*`, you can simply get a calendar using `Calendar.objects.get(user=followed)`, by this you can easily get the calendar's id.

```Calendar.objects.get(user=followed)``` seem to cause a error when run this line. I don't know why.

**Comment by natchanon-space** [comment]
@patkamon There is no new migration file for new added field, did you run `python manage.py makemigrations`?
I can't make load your new fixture without it.

Maybe I found the problem in the tests.
For the problem in your test, as example you can fix it this way (for `test_me` in follow status part)

old (has problem and randomly choose which is definately not calendar for `followed`)
```python
def test_me_followed_post(self):
        self.client = authenticated_client_factory(self.user)
        followed = User(username="followed", password="followed")
        calendar = Calendar(
            user=followed,
            name=followed.username,
            slug=generate_slug(followed.username)
        )
        followed.save()
        response = self.client.post(
            reverse('api_v2:me_follow'),
            data = {
                "option": "follow",
                "follow_id": followed.id,
                "follow_calendar": 1,
                }
        )
        self.assertEqual(HTTP_201_CREATED, response.status_code)
```

new
```
def test_me_followed_post(self):
        self.client = authenticated_client_factory(self.user)
        followed = User(username="followed", password="followed")
        followed.save() # save first so you got is id and you can use this to create new calendar
        calendar = Calendar(
            user=followed,
            name=followed.username,
            slug=generate_slug(followed.username)
        )
        calendar.save() # same reason with the followed.save()
        response = self.client.post(
            reverse('api_v2:me_follow'),
            # change follow_calendar data because 1 is not his calendar (calendar w/ 1 is already created in setUp())
            data = {
                "option": "follow",
                "follow_id": followed.id,
                "follow_calendar":  calendar.id,
                }
        )
        self.assertEqual(HTTP_201_CREATED, response.status_code)
```

**Comment by patkamon** [comment]
I have fixing it follow by @natchanon-space comment. Please check again.

**Review by natchanon-space — APPROVED** [review]
Approved!

**Review by Thanabardi — APPROVED** [review]

**Pull request merged**
