### PR TITLE
User setting

### PR DESCRIPTION
**Pull request by touchtool**
- Tag can change color.
- Three themes of the calendar can select.
- User has an image, description and custom name.

### CODE REVIEW

**Comment by Thanabardi** [comment]
I see that when I upload a new non square picture, my profile picture is resized(squeezed) to be square not cropped. Do you have a plan to fix that?

**Comment by touchtool** [comment]
Sure, The picture that resized. I will try to fix it as soon as possible.

**Comment by HuskyIsHere** [comment]
There are problems that user cannot use the default tags.

**Review by natchanon-space — APPROVED** [review]
Working is fine. 

Somethings that I found:
At create event, the default tags and private tag is not available. We should be able create event with these tags, right?
In my opinion color setting (showing how the color changed using text color) is hard to see.

**Comment by Thanabardi** [comment]
@natchanon-space Alright, I'll fix it at my `tag-config` branch.

**Comment by patkamon** [comment]
Screen Shot 2564-11-20 at 00 29 50
First I think center was a bit off to the left for macOS don't know about windowOS (recommend using % instead of px in css)
Second in setting page it kinda hard to see cursor when switching between theme I recommend to make hover on element such as color circle and upload image button (can be enhancement in next iteration).

**Comment by touchtool** [comment]
@Thanabardi fixed image squeeze.

**Review by patkamon — APPROVED** [review]

**Review by Thanabardi — APPROVED** [review]

**Review by HuskyIsHere — APPROVED** [review]

**Pull request merged**
