### PR TITLE
App template

### PR DESCRIPTION
**Pull request by patkamon**
A epic assemble branch. that collect from

1. month-button  
   1. change month button to year 
3. sidebar-enhance-it4
   1. modify outlooks
   2. add follow button
   3. add tag 
3. follow-button
   1. connect with api v2 and auth to come up with skdue that can follow other user.
4. navbar
   1. modify  event create for api v2
5. filter-tag
    1. connect with api v2 to come up with calendar events that can turn on and off from calendar tag

### CODE REVIEW

**Review by Thanabardi — APPROVED** [review]
Everything looks great!

**Review by touchtool — APPROVED** [review]
Evertything fine now!

**Review by HuskyIsHere — CHANGES_REQUESTED** [review]
There are problem when you want to create the event you got the tag of user that you are follow.

**Review by HuskyIsHere — APPROVED** [review]

**Review by Thanabardi — APPROVED** [review]

**Review by natchanon-space — APPROVED** [review]
Nice! I'll deploy this ASAP.

**Pull request merged**
