### PR TITLE
Fix auth

### PR DESCRIPTION
**Pull request by natchanon-space**
Pls, help me test this things.
What I've done: Change authentication to token based.

WARNING: There are some fail test in `test_user_me.py`, due to the change of authentication.

### CODE REVIEW

**Review by HuskyIsHere — APPROVED** [review]
Private view and public view both are working correctly.

**Review by touchtool — APPROVED** [review]
Everything works fine!

**Review by patkamon — APPROVED** [review]
Nice!

**Review by Thanabardi — APPROVED** [review]
Seems good

**Pull request merged**
