### PR TITLE
Second version successfully deployed!

### PR DESCRIPTION
**Pull request by natchanon-space**
Check this, [skdue](http://www.skdue.site)

Changes: 
* using new fixture data `calendar_deploy_2` as default data.
* remove some old unusable fixtures.
* archive API v1

### CODE REVIEW

**Review by patkamon — APPROVED** [review]
Flawless.

**Review by touchtool — APPROVED** [review]
Nice!

**Review by HuskyIsHere — APPROVED** [review]
Nice work.

**Review by Thanabardi — APPROVED** [review]
Let's goo

**Pull request merged**
